export default {
  // Counter
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',
  //Firebase
  ADD_HABIT: 'ADD_HABIT',
  ADD_HABIT_ERR: 'ADD_HABIT_ERR',
  GET_HABITS: 'GET_HABITS',
  GET_HABITS_ERR: 'GET_HABITS_ERR',
}
