export default {
  // Counter
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',
  //Firebase
  BULK_ADD_HABITS: 'BULK_ADD_HABITS',
  ADD_HABIT: 'ADD_HABIT',
  ADD_HABIT_ERR: 'ADD_HABIT_ERR',
  GET_HABITS: 'GET_HABITS',
  GET_HABITS_ERR: 'GET_HABITS_ERR',
  ON_NEW_HABIT_CHANGE: 'ON_NEW_HABIT_CHANGE',
  DELETE_HABIT: 'DELETE_HABIT',
  DELETE_HABIT_ERR: 'DELETE_HABIT_ERR',
  UPDATE_HABIT: 'UPDATE_HABIT',
  UPDATE_HABIT_ERR: 'UPDATE_HABIT_ERR',
  LOAD_HABIT_EDITOR: 'LOAD_HABIT_EDITOR',
  RESET_HABIT_EDITOR: 'RESET_HABIT_EDITOR',
}
