export default {
  // Counter
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',
  //Firebase
  BULK_ADD_HABITS: 'BULK_ADD_HABITS',
  ADD_HABIT: 'ADD_HABIT',
  ADD_HABIT_ERR: 'ADD_HABIT_ERR',
  GET_HABITS: 'GET_HABITS',
  GET_HABITS_ERR: 'GET_HABITS_ERR',
  UPDATE_NEW_HABIT_PARAM: 'UPDATE_NEW_HABIT_PARAM',
}
